version: '3.0'

services:
  grafana:
    # image: grafana/grafana:latest
    container_name: 'dashboard-reporter-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/dashboard-reporter-app
      - ./provisioning:/etc/grafana/provisioning
    environment:
      # basic settings
      # output to terminal
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      # - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      # allow anonymous admin so we don't have to set up a password to start testing
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # skip login page
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      # disable alerting because it vomits logs
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
